### PR TITLE
retrieve correct cardinality for columnstore scan

### LINKED ISSUE #124: Report correct row count in columnstore tables
### What feature are you requesting?

Whether it's a join between Mooncake and a local PG table or a join between two tables within Mooncake, both are relatively slow. I'm not sure why.  

```
CREATE TABLE user_activity(    
  user_id BIGINT,    
  activity_type TEXT,    
  activity_timestamp TIMESTAMP,    
  duration INT    
) USING columnstore;    

INSERT INTO user_activity VALUES    
  (1, 'login', '2024-01-01 08:00:00', 120),    
  (2, 'page_view', '2024-01-01 08:05:00', 30),    
  (3, 'logout', '2024-01-01 08:30:00', 60),    
  (4, 'error', '2024-01-01 08:13:00', 60);    

postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 4  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 8  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 16  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 32  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 64  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 128  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 256  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 512  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 1024  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 2048  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 4096  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 8192  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 16384  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 32768  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 65536  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 131072  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 262144  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 524288  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 1048576  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 2097152  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 4194304  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 8388608  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 16777216  
postgres=# insert into user_activity select * from user_activity ;  
INSERT 0 67108864  
postgres=# insert into user_activity select * from user_activity ; 
INSERT 0 134217728
postgres=# select count(*) from user_activity ;  
   count   
-----------
 268435456
(1 row)
Time: 264.244 ms
postgres=# select count(distinct user_id) from user_activity ;  
 count 
-------
     4
(1 row)
Time: 1152.456 ms (00:01.152)
```
   
```
// local table join mooncake table
postgres=# create table localtbl(id int8, info text);  
CREATE TABLE  
postgres=# insert into localtbl select generate_series(1,1000), md5(random()::text);  
INSERT 0 1000 
postgres=# select count(distinct t2.user_id) from localtbl t1 join user_activity t2 on (t1.id=t2.user_id);  
 count   
-------  
     4  
(1 row)  
Time: 95722.228 ms (01:35.722)  


// mooncake table join mooncake table , also very slow.  
create table moontbl(id int8, info text) USING columnstore ;
insert into  moontbl select x, md5(random()::text) from generate_series(1,1000) x; 
select count(distinct t2.user_id) from moontbl t1 join user_activity t2 on (t1.id=t2.user_id);
```

However, if I directly use DuckDB to join two DuckDB tables, it is much faster. 

Thank you.
  

### Why are you requesting this feature?

Joins are a very common operation, and based on the observed behavior, they shouldn't be this slow. I wonder if there might be other underlying reasons causing this issue?

### What is your proposed implementation for this feature?

Can more detailed log output be enabled in `EXPLAIN VERBOSE` or `EXPLAIN ANALYZE` to help improve analysis efficiency?

### PR DESCRIPTION
**Pull request by YuweiXiao**
Compute cardinality from file metadata when initialize the columnstore scan, to ensure duckdb generates an optimal query plan.

fix #124

### CODE REVIEW

File: src/columnstore/execution/columnstore_scan.cpp [hunk 1]
```diff
@@ -153,7 +153,11 @@ TableFunction ColumnstoreTable::GetScanFunction(ClientContext &context, unique_p
     }
     vector<Value> inputs;
     inputs.push_back(Value::LIST(values));
+    idx_t carinality = Cardinality(file_names);
     named_parameter_map_t named_parameters{{"file_row_number", Value(true)}};
+    if (carinality > 0) {
+        named_parameters["explicit_cardinality"] = Value::UBIGINT(carinality);
+    }
```
Comment (nbiscaro) [inline src/columnstore/execution/columnstore_scan.cpp:160]: typo:
```suggestion
    idx_t cardinality = Cardinality(file_names);
    named_parameter_map_t named_parameters{{"file_row_number", Value(true)}};
    if (cardinality > 0) {
        named_parameters["explicit_cardinality"] = Value::UBIGINT(cardinality);
    }
```

File: src/columnstore/columnstore_statistics.hpp [hunk 2]
```diff
@@ -26,7 +26,12 @@ class DataFileStatistics : public ObjectCacheEntry {
         return column_stats.at(name).get();
     }
 
+    idx_t NumRows() {
+        return num_rows;
+    }
+
```
Comment (dpxcc) [inline src/columnstore/columnstore_statistics.hpp:32]: nit: move `NumRows()` before `Get()`

File: src/columnstore/columnstore_table.cpp [hunk 3]
```diff
@@ -280,4 +281,15 @@ vector<string> ColumnstoreTable::GetFilePaths(const string &path, const vector<s
     return file_paths;
 }
 
+idx_t ColumnstoreTable::Cardinality(const vector<string> &file_names) {
+    idx_t cardinality = 0;
+    for (auto &file_name : file_names) {
+        auto file_stats = columnstore_stats.Get<DataFileStatistics>(file_name);
+        if (file_stats) {
```
Comment (dpxcc) [inline src/columnstore/columnstore_table.cpp:288]: `file_stats` can't be null

File: src/columnstore/columnstore_table.hpp [hunk 4]
```diff
@@ -38,6 +38,8 @@ class ColumnstoreTable : public TableCatalogEntry {
 private:
     vector<string> GetFilePaths(const string &path, const vector<string> &file_names);
 
+    idx_t Cardinality(const vector<string> &file_names);
```
Comment (dpxcc) [inline src/columnstore/columnstore_table.hpp:41]: can we make both `static`?

File: src/columnstore/execution/columnstore_scan.cpp [hunk 5]
```diff
@@ -153,7 +153,11 @@ TableFunction ColumnstoreTable::GetScanFunction(ClientContext &context, unique_p
     }
     vector<Value> inputs;
     inputs.push_back(Value::LIST(values));
+    idx_t carinality = Cardinality(file_names);
     named_parameter_map_t named_parameters{{"file_row_number", Value(true)}};
+    if (carinality > 0) {
```
Comment (dpxcc) [inline src/columnstore/execution/columnstore_scan.cpp:158]: why testing `cardinality > 0`?
just
```cpp
named_parameter_map_t named_parameters{{"file_row_number", Value(true)},
                                       {"explicit_cardinality", Value::UBIGINT(Cardinality(file_names))}};
```

File: src/columnstore/columnstore_statistics.cpp [hunk 6]
```diff
@@ -4,6 +4,7 @@
 namespace duckdb {
 
 DataFileStatistics::DataFileStatistics(ParquetReader &reader, const ColumnList &columns) {
+    num_rows = reader.NumRows();
```
Comment (dpxcc) [inline src/columnstore/columnstore_statistics.cpp:7]: nit: use initializer list

File: src/columnstore/execution/columnstore_scan.cpp (hunk 5 above)
Comment (YuweiXiao) [reply src/columnstore/execution/columnstore_scan.cpp:158]: Updated.

was afraid we do not have metadata in PG side, so would be better to fallback to letting `parquet_scan` decide the cardinality.

**Comment by YuweiXiao** [comment]
@dpxcc hey, comments are addressed. also added a regress test.

File: test/expected/cardinality.out [hunk 7]
```diff
@@ -0,0 +1,86 @@
+CREATE TABLE t (a int) USING columnstore;
```
Comment (dpxcc) [inline test/expected/cardinality.out:1]: Running `make installcheck` inside our devcontainer fails with
```
diff -U3 /workspaces/pg_mooncake/test/expected/cardinality.out /workspaces/pg_mooncake/build/debug/results/cardinality.out
--- /workspaces/pg_mooncake/test/expected/cardinality.out	2025-02-20 04:13:57.285389447 +0000
+++ /workspaces/pg_mooncake/build/debug/results/cardinality.out	2025-02-20 04:17:47.345297775 +0000
@@ -1,8 +1,8 @@
 CREATE TABLE t (a int) USING columnstore;
 INSERT INTO t SELECT i FROM generate_series(1, 100) i;
 EXPLAIN SELECT * FROM t;
-                             QUERY PLAN                             
---------------------------------------------------------------------
+                                       QUERY PLAN                                        
+-----------------------------------------------------------------------------------------
  Custom Scan (MooncakeDuckDBScan)  (cost=0.00..0.00 rows=0 width=0)
    DuckDB Execution Plan: 
  
@@ -22,8 +22,8 @@
 
 INSERT INTO t SELECT i FROM generate_series(1, 200) i;
 EXPLAIN SELECT * FROM t;
-                             QUERY PLAN                             
---------------------------------------------------------------------
+                                       QUERY PLAN                                        
+-----------------------------------------------------------------------------------------
  Custom Scan (MooncakeDuckDBScan)  (cost=0.00..0.00 rows=0 width=0)
    DuckDB Execution Plan: 
  
@@ -43,8 +43,8 @@
 
 INSERT INTO t SELECT i FROM generate_series(1, 400) i;
 EXPLAIN SELECT * FROM t;
-                             QUERY PLAN                             
---------------------------------------------------------------------
+                                       QUERY PLAN                                        
+-----------------------------------------------------------------------------------------
  Custom Scan (MooncakeDuckDBScan)  (cost=0.00..0.00 rows=0 width=0)
    DuckDB Execution Plan: 
  
@@ -64,8 +64,8 @@
 
 INSERT INTO t SELECT i FROM generate_series(1, 800) i;
 EXPLAIN SELECT * FROM t;
-                             QUERY PLAN                             
---------------------------------------------------------------------
+                                       QUERY PLAN                                        
+-----------------------------------------------------------------------------------------
  Custom Scan (MooncakeDuckDBScan)  (cost=0.00..0.00 rows=0 width=0)
    DuckDB Execution Plan: 
  
```
I looked into the issue and it seems that we need to pass `--encoding=UTF8` to `REGRESS_OPTS` in `Makefile.build`

BTW it's strongly recommended to use our devcontainer to normalize the dev environment: https://github.com/Mooncake-Labs/pg_mooncake/blob/main/CONTRIBUTING.md

**Comment by dpxcc** [comment]
Thanks for working on this!!
